name: Build

on:
  workflow_dispatch:
    inputs:
      useCache:
        description: Use GHA cache
        type: boolean
        required: false
        default: true
  push:
    branches-ignore:
      - "update-dependencies-pr"
    paths:
      - ".github/workflows/build.yml"
      - "docker/**"
      - "tests/**"
      - "*.sh"
  pull_request:
    paths:
      - ".github/workflows/build.yml"
      - "docker/**"
      - "tests/**"
      - "*.sh"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build_manylinux2014_base:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get tag name
        id: tag
        run: |
          COMMIT_DATE=$(git show -s --format=%cd --date=short ${{ github.sha }})
          if $(git rev-parse --is-shallow-repository); then
            git fetch --unshallow
          fi
          BUILD_NUMBER=$(git rev-list --since=${COMMIT_DATE}T00:00:00Z --first-parent --count ${{ github.sha }})
          BUILD_ID2=${COMMIT_DATE//-/.}-${BUILD_NUMBER}
          echo "tag=${BUILD_ID2}" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay.io
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          platforms: linux/arm64,linux/x86_64,linux/386,linux/ppc64le,linux/s390x
          load: false
          push: true
          tags: quay.io/pypa/manylinux2014_base:latest,quay.io/pypa/manylinux2014_base:${{ steps.tag.outputs.tag }}
